version: '3'
services:
    nginx:
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./nginx/logs:/var/log/nginx
        - ./nginx/sites-available:/etc/nginx/sites-available
      ports:
        - 80:80
        - 443:443
