version: '3'
services:
    nginx:
      build: .
      volumes:
        - ./nginx/logs:/var/log/nginx
        - ./nginx/sites-available:/etc/nginx/sites-available
      ports:
        - 80:80
        - 443:443
      networks:
        - mephisto-net
networks:
    mephisto-net:
